In [1]:
import numpy as np
import scipy

In [1]:
!pip install scipy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
paulis = [
    [[1, 0], [0, 1]],
    [[0, 1], [1, 0]],
    [[0, -1j], [1j, 0]],
    [[1, 0], [0, -1]]
]

paulis = np.array(paulis, dtype=np.complex128)

In [7]:
h = [[1, 1], [1, -1]]
h = 0.5 * np.sqrt(2) * np.array(h, dtype=np.complex128)

for pauli in paulis:
    print(np.matmul(h, pauli))
    print()

[[ 0.70710678+0.j  0.70710678+0.j]
 [ 0.70710678+0.j -0.70710678+0.j]]

[[ 0.70710678+0.j  0.70710678+0.j]
 [-0.70710678+0.j  0.70710678+0.j]]

[[0.+0.70710678j 0.-0.70710678j]
 [0.-0.70710678j 0.-0.70710678j]]

[[ 0.70710678+0.j -0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]



### Hadamard

In [5]:
h = [[1, 1], [1, -1]]
h = 0.5 * np.sqrt(2) * np.array(h, dtype=np.complex128)

h

array([[ 0.70710678+0.j,  0.70710678+0.j],
       [ 0.70710678+0.j, -0.70710678+0.j]])

In [7]:
np.matmul(paulis[2], np.matmul(h, paulis[2]))

array([[-0.70710678+0.j, -0.70710678+0.j],
       [-0.70710678+0.j,  0.70710678+0.j]])

In [5]:
for pauli in paulis:
    print(np.matmul(np.matmul(h, pauli), h))

[[1.00000000e+00+0.j 4.26642159e-17+0.j]
 [4.26642159e-17+0.j 1.00000000e+00+0.j]]
[[ 1.00000000e+00+0.j  4.26642159e-17+0.j]
 [-4.26642159e-17+0.j -1.00000000e+00+0.j]]
[[0.+4.26642159e-17j 0.+1.00000000e+00j]
 [0.-1.00000000e+00j 0.-4.26642159e-17j]]
[[4.26642159e-17+0.j 1.00000000e+00+0.j]
 [1.00000000e+00+0.j 4.26642159e-17+0.j]]


### S (Phase)

In [8]:
s = [[1, 0], [0, 1j]]
s = np.array(s, dtype=np.complex128)

s

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

In [10]:
for pauli in paulis:
    print(np.matmul(np.matmul(np.conj(s.T), pauli), s))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
[[0.+0.j 0.+1.j]
 [0.-1.j 0.+0.j]]
[[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]
[[ 1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]


### CNOT

In [7]:
cx = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]]
cx = np.array(cx, dtype=np.complex128)

cx

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]])

In [12]:
for pauli in paulis:
    for other_pauli in paulis:
        pauli_op = np.kron(pauli, other_pauli)

        print(np.matmul(np.matmul(cx, pauli_op), cx))

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]
[[0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]]
[[0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+1.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]]
[[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j]]
[[0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [1.+0.j 0.+0.j 0.+0.j 0.+0.j]]
[[0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]]
[[0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.+0.j]]
[[ 0.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [ 0.+0.j  0.+0.j -1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j  0.+0.j  0.+0.j]
 [ 1

### KAK decomposition of CNOT

In [39]:
hadamard = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

kak_params = np.array([1 / np.sqrt(2), 1j / np.sqrt(2), 0, 0]).astype(np.complex128)
paulis = [
    [[1, 0], [0, 1]],
    [[0, 1], [1, 0]],
    [[0, -1j], [1j, 0]],
    [[1, 0], [0, -1]]
]

paulis = np.array(paulis).astype(np.complex128)

cnot_kak_nonlocal = scipy.linalg.expm(1j * 0.25 * np.pi * np.kron(paulis[1], paulis[1]))
    
print(cnot_kak_nonlocal)

print(np.matmul(np.matmul(np.kron(paulis[0], hadamard), cnot_kak_nonlocal), np.kron(hadamard, hadamard)))

[[0.70710678+0.j         0.        +0.j         0.        +0.j
  0.        +0.70710678j]
 [0.        +0.j         0.70710678+0.j         0.        +0.70710678j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.70710678j 0.70710678+0.j
  0.        +0.j        ]
 [0.        +0.70710678j 0.        +0.j         0.        +0.j
  0.70710678+0.j        ]]
[[ 0.5+5.00000000e-01j  0. -1.23259516e-32j  0.5-5.00000000e-01j
   0. +1.23259516e-32j]
 [ 0. +1.23259516e-32j  0.5-5.00000000e-01j  0. -1.23259516e-32j
   0.5+5.00000000e-01j]
 [ 0.5+5.00000000e-01j  0. -1.23259516e-32j -0.5+5.00000000e-01j
   0. -1.23259516e-32j]
 [ 0. +1.23259516e-32j  0.5-5.00000000e-01j  0. +1.23259516e-32j
  -0.5-5.00000000e-01j]]


In [23]:
import qiskit

In [100]:
cnot_matrix = np.array(
    [
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
    ]
)

ret = qiskit.synthesis.TwoQubitWeylDecomposition(cnot_matrix)

In [102]:
ret

TwoQubitWeylDecomposition.from_bytes(
    # TwoQubitWeylDecomposition [specialization=ControlledEquiv] (
    # 	global phase: π/4
    # 	       ┌──────────┐ ┌────────┐┌────────────┐ ┌─────────┐ ┌─────────┐
    # 	q_0: ──┤ Ry(-π/2) ├─┤ Rx(-π) ├┤0           ├─┤ Rx(π/2) ├─┤ Ry(π/2) ├
    # 	     ┌─┴──────────┴┐├───────┬┘│  Rxx(-π/2) │┌┴─────────┴┐└┬───────┬┘
    # 	q_1: ┤ Rx(-2.1873) ├┤ Ry(π) ├─┤1           ├┤ Rx(2.525) ├─┤ Ry(π) ├─
    # 	     └─────────────┘└───────┘ └────────────┘└───────────┘ └───────┘
    # )
    b'k05VTVBZAQB2AHsnZGVzY3InOiAnPGMxNicsICdmb3J0cmFuX29yZGVyJzogRmFsc2UsICdzaGFw'
    b'ZSc6ICg0LCA0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg'
    b'ICAgICAgICAgICAgIAoAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

In [3]:
paulis = [
    [[1, 0], [0, 1]],
    [[0, 1], [1, 0]],
    [[0, -1j], [1j, 0]],
    [[1, 0], [0, -1]]
]

paulis = np.array(paulis)


def rx(angle):
    return scipy.linalg.expm(-1j * 0.5 * angle * paulis[1])


def ry(angle):
    return scipy.linalg.expm(-1j * 0.5 * angle * paulis[2])


def rxx(angle):
    return scipy.linalg.expm(-1j * 0.5 * angle * np.kron(paulis[1], paulis[1]))

In [104]:
4 * np.pi / 6

2.0943951023931953

In [105]:
gate_1 = np.kron(np.matmul(rx(-np.pi), ry(np.pi / 2)), np.matmul(rx(-np.pi), np.matmul(ry(np.pi), rx(np.pi))))
gate_2 = rxx(-np.pi / 2)
gate_3 = np.kron(np.matmul(rx(np.pi / 2), ry(np.pi / 2)), np.matmul(rx(np.pi / 2), ry(np.pi)))

In [106]:
np.matmul(np.matmul(gate_1, gate_2), gate_3)

array([[ 7.07106781e-01+7.07106781e-01j,  0.00000000e+00+0.00000000e+00j,
         5.55111512e-17+5.55111512e-17j, -7.85046229e-17-7.85046229e-17j],
       [ 0.00000000e+00+0.00000000e+00j,  7.07106781e-01+7.07106781e-01j,
        -7.85046229e-17-7.85046229e-17j,  5.55111512e-17+5.55111512e-17j],
       [ 5.55111512e-17+5.55111512e-17j, -5.55111512e-17-5.55111512e-17j,
         1.11022302e-16-1.11022302e-16j,  7.07106781e-01+7.07106781e-01j],
       [-5.55111512e-17-5.55111512e-17j,  5.55111512e-17+5.55111512e-17j,
         7.07106781e-01+7.07106781e-01j,  1.11022302e-16-1.11022302e-16j]])

In [4]:
np.matmul(rx(-np.pi), np.matmul(ry(np.pi), rx(np.pi)))

array([[ 0.+0.j,  1.+0.j],
       [-1.+0.j,  0.+0.j]])

In [5]:
np.matmul(paulis[3], paulis[1])

array([[ 0.+0.j,  1.+0.j],
       [-1.+0.j,  0.+0.j]])